# redis服务器的配置信息
redis:
  port: 6379
  host: 127.0.0.1

# github.com/ecomfe/api的代码地址
repos:
  api: /Users/leeight/local/leeight.github.com/edp-cli/api

npm:
  _auth: ZWNvbWZlOmVjb21mZWF0YmVpamluZyZzaGFuZ2hhaQ==
  registry: http://registry.edp.baidu.com/
  email: ecomfe@gmail.com
  proxy: null
  https-proxy: null
  http-proxy: null
